# MATH training dataset (excluding MATH-500)
# @package _global_.dataset

_target_: src.data.datasets.math_train.MathTrainDataset

split: "train"
max_examples: null
seed: ${seed}

# Dataset-specific settings
hf_path: "appier-ai-research/MATH-train-11498"
verification_mode: "math_verify"  # or "llm_judge"
llm_judge_model: "openai/gpt-oss-20b"
llm_judge_base_url: null
llm_judge_max_concurrent: 1000
